<a href="https://colab.research.google.com/github/mohammadalkhawaldah/105/blob/main/Numpy2_24_11_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2])

In [ ]:
b= np.array([3,4])

In [ ]:
c = a.dot(b)

In [ ]:
c

11

In [ ]:
a*b

array([3, 8])

In [ ]:
a@b

11

In [ ]:
(a*b).sum()

11

In [ ]:
(a*a).sum()

5

In [ ]:
mag = np.sqrt((a*a).sum())

In [ ]:
mag

2.23606797749979

In [ ]:
mag2 = np.linalg.norm(b)

In [ ]:
mag2

5.0

In [ ]:
x = a.dot(b)/(np.linalg.norm(a) * np.linalg.norm(b))

In [ ]:
x

0.9838699100999074

In [ ]:
ang = np.arccos(x)

In [ ]:
ang

0.17985349979247847

## **Matricies**


In [ ]:
L =[[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0]

[1, 2]

In [ ]:
L[1]

[3, 4]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2], [3,4]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[1, :]

array([3, 4])

In [ ]:
A[1,1]

4

In [ ]:
A[0,1]

2

In [ ]:
A[:,0]

array([1, 3])

In [ ]:
A[0, :]

array([1, 2])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])

In [ ]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
B[:,1]

array([2, 5])

In [ ]:
B[1, :]

array([4, 5, 6])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
np.diag(A).T

array([1, 4])

In [ ]:
a = np.diag (A)

In [ ]:
a

array([1, 4])

In [ ]:
a.T

array([1, 4])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((5,7)) * 10

array([[10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10.]])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.random((7,9))

array([[0.4637927 , 0.09014907, 0.97383009, 0.30858562, 0.99353737,
        0.72167081, 0.21295334, 0.79703334, 0.55258413],
       [0.88844873, 0.39926988, 0.12894442, 0.4591828 , 0.82723852,
        0.39666355, 0.93327397, 0.67853751, 0.47912421],
       [0.40958616, 0.67229729, 0.85862529, 0.74279213, 0.93790231,
        0.3010399 , 0.21343384, 0.78206647, 0.57239543],
       [0.47606756, 0.09562157, 0.50405371, 0.5920152 , 0.20743332,
        0.52417531, 0.00646941, 0.99672817, 0.52840208],
       [0.63658934, 0.66092161, 0.22895656, 0.27659011, 0.24209993,
        0.20387634, 0.67030394, 0.97005969, 0.29401017],
       [0.71484594, 0.99669815, 0.55203478, 0.37422324, 0.32808941,
        0.71221284, 0.3328857 , 0.19140566, 0.27721113],
       [0.42910811, 0.78647926, 0.15070229, 0.99927515, 0.03705274,
        0.63212452, 0.9677248 , 0.64581429, 0.71148271]])

In [ ]:
np.random. (7,9)

array([[-2.35056396, -0.40457508,  1.07032976, -2.41968454, -0.91298731,
         2.92378634, -1.47884919,  1.46095605, -0.7876569 ],
       [-0.67396101, -0.06866185,  1.59205893,  0.03558249, -1.69302019,
         0.32682132, -0.22071327, -0.64836292, -1.75043837],
       [ 1.68567764, -1.77492266, -0.54543836,  1.22988829,  0.56367471,
        -1.37171408, -0.66521213,  0.31154164,  1.51796908],
       [-1.48088507, -1.33981731,  0.11152769,  0.25997194, -2.45593285,
        -0.74863217, -0.09670425, -0.35858147,  0.3802122 ],
       [-0.73616097, -0.45779364,  0.31855583,  0.68172344,  1.13439404,
         0.99061811,  1.29158169,  0.05663684,  0.59018455],
       [-0.72997946,  0.76737746,  0.13761156,  1.34186081,  0.10232789,
         1.01355374,  1.86181856, -0.03055273,  1.67928846],
       [-1.57361629,  0.73441479, -0.77299363,  0.41014076,  0.11300045,
         0.43640973, -0.8056985 , -0.33848566, -0.26301911]])